# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time:     "08:30"
      timezone: "Europe/Berlin"

  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-6.0"
    schedule:
      interval: "daily"
      time:     "08:30"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "rails"
        update-type: # keep only patch level
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-6.1"
    schedule:
      interval: "daily"
      time:     "08:30"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "rails"
        update-type: # keep only patch level
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-7.0"
    schedule:
      interval: "daily"
      time:     "08:30"
      timezone: "Europe/Berlin"
    ignore:
      - dependency-name: "rails"
        update-type: # keep only patch level
          - version-update:semver-major
          - version-update:semver-minor

  - package-ecosystem: "bundler"
    directory: "/gemfiles/rails-main"
    schedule:
      interval: "weekly" # volatile, avoid daily PRs
      time:     "08:30"
      timezone: "Europe/Berlin"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time:     "08:30"
      timezone: "Europe/Berlin"
