# frozen_string_literal: true

source "https://rubygems.org"
gemspec path: "../.."

gem "pry-byebug"
gem "rails", "~> 7.2.0.beta3"

gem "concurrent-ruby", "1.3.4"

# keep in sync with ../../Gemfile
group :development, :test do
  gem "combustion"
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.0"
  gem "rspec-rails"
end
