# frozen_string_literal: true

source "https://rubygems.org"
gemspec path: "../.."

gem "pry-byebug"
gem "rails", "~> 6.1.7"

eval File.read File.join(__dir__, "../common.rb") # rubocop:disable Security/Eval
