# frozen_string_literal: true

source "https://rubygems.org"
gemspec path: "../.."

gem "nokogiri", "~> 1.15.6" # remove constraint when min. RUBY_VERSION >= 3
gem "pry-byebug"
gem "rails", "~> 6.1.7"

# keep in sync with ../../Gemfile
group :development, :test do
  gem "combustion"
  gem "rake", "~> 13.2"
  gem "rspec", "~> 3.0"
  gem "rspec-rails"
end
