# frozen_string_literal: true

source "https://rubygems.org"
gemspec path: "../.."

gem "pry-byebug"
gem "rails", github: "rails/rails", branch: "main"

# keep in sync with ../../Gemfile
group :development, :test do
  gem "combustion"
  gem "rake", "~> 13.1"
  gem "rspec", "~> 3.0"
  gem "rspec-rails"
end
