name: Rails Pre-Release

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}/Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:  ['3.1', '3.2', '3.3']
        rails: ['main', '7.2']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails-${{ matrix.rails }}/Gemfile

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Start texd container
      run: |
        docker run --rm -d --name texd-dev \
          -p 2201:2201 \
          -e HOME=/tmp \
          -v $(mktemp -d):/texd \
          -v $(mktemp -d):/refs \
          --user=$(id -u):$(id -g) \
            ghcr.io/digineo/texd --reference-store dir:///refs

        until curl -fs -o/dev/null http://localhost:2201/status; do sleep 2; echo waiting for texd; done

    - name: Run rspec
      run: bundle exec rake spec
