name: Ruby

on:
  push:
    branches:
      - master
    paths:
      - gemfiles/rails-main/Gemfile*
  pull_request:
    paths:
      - gemfiles/rails-main/Gemfile*

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}/Rails ${{ matrix.rails }}
    strategy:
      matrix:
        ruby:  ['2.7', '3.0', '3.1']
        rails: ['main']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails-${{ matrix.rails }}/Gemfile

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ github.event_name != 'pull_request' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Start texd container
      run: |
        docker run --rm -d --name texd-dev \
          -p 2201:2201 \
          -v $(mktemp -d):/texd \
          -v $(mktemp -d):/refs \
          --user=$(id -u):$(id -g) \
            digineode/texd --reference-store dir:///refs

        until curl -fs -o/dev/null http://localhost:2201/status; do sleep 2; echo waiting for texd; done

    - name: Run rspec
      run: bundle exec rake spec
