name: Rails Main

on:
  push:
    paths:
      - gemfiles/rails-main/Gemfile*
  pull_request:
    paths:
      - gemfiles/rails-main/Gemfile*

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:  ['3.1', '3.2']

    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails-main/Gemfile

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Start texd container
      run: |
        docker run --rm -d --name texd-dev \
          -p 2201:2201 \
          -v $(mktemp -d):/texd \
          -v $(mktemp -d):/refs \
          --user=$(id -u):$(id -g) \
            ghcr.io/digineo/texd --reference-store dir:///refs

        until curl -fs -o/dev/null http://localhost:2201/status; do sleep 2; echo waiting for texd; done

    - name: Run rspec
      run: bundle exec rake spec
